allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

subprojects {
    project.afterEvaluate {
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace = project.group
                }
                compileSdk = 35
                buildToolsVersion = "35.0.0"
                defaultConfig {
                    if (targetSdk == null) {
                        targetSdk = 35
                    }
                    if (minSdk == null) {
                        minSdk = 21
                    }
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
